require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


target 'stransporte_app' do
  config = use_native_modules!
  flags = get_default_flags()
  use_react_native!(:path => config[:reactNativePath],

  # Hermes is now enabled by default. Disable by setting this flag to false.
  # Upcoming versions of React Native may rely on get_default_flags(), but
  # we make it explicit here to aid in the React Native upgrade process.
  :hermes_enabled => flags[:hermes_enabled],
  :fabric_enabled => flags[:fabric_enabled],
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  :flipper_configuration => flipper_config,
  # An absolute path to your application root.
  :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Google-Maps-iOS-Utils'
  
  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
#  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

end

