name: "CI/CD SERVISOFTS - ANDROID"
on:
  push:
    branches: ["main"]

jobs:
  compile_android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Load secrets
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: .github/actions/decode_secrets.sh $SECRET_KEY


      - name: Instalando el Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: ./bin/version
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Build release aab
        run: cd android && ./gradlew bundleRelease --stacktrace

      - name: Upload aab
        uses: actions/upload-artifact@master
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release.aab

      - run: .github/actions/load_env.sh ANDROID_PACKAGE_NAME
      - name: Publish to Play Store beta track
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJson: android/app/service-account.json
          packageName: ${{env.ANDROID_PACKAGE_NAME}}
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          inAppUpdatePriority: 2

      - name: Clean files
        if: ${{ always() }}
        run: |
          ./bin/secrets clean
