name: "CI/CD SERVISOFTS - WEB"
on:
  push:
    branches: ["dev"]

jobs:
  compile_web:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Load secrets
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: .github/actions/decode_secrets.sh $SECRET_KEY

      - name: Set up SSH Key
        run: .github/actions/ssh_setup.sh

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Instalando el Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: ./bin/version
      - run: npm run build
      - name: Deploy with rsync
        run: .github/actions/web_copy_build.sh
      - name: Clean files
        if: ${{ always() }}
        run: |
          ./bin/secrets clean
